[server]
url = ''
username = ''
auth_method = 'plaintext' # Options: 'plaintext', 'hashed', 'api_key'

# Required if auth_method = 'plaintext'
password = ''

# Required if auth_method = 'hashed'
password_token = ''
password_salt = ''

# Required if auth_method = 'api_key'
api_key = ''

[security]
redact_credentials_in_logs = true